### ISSUE TITLE
cant seem to get working

### ISSUE THREAD

**Issue by reitenth** [nikarh/jellyfin-plugin-authelia#52]
![image](https://github.com/nikarh/jellyfin-plugin-authelia/assets/94771708/7f7969ef-aab8-4c04-98fb-8f4a2f5b60e8)

**Comment by reitenth** [comment]
my authelia server in the settings works
jellyfin url is one of what i have under the second "domain" in the ss.

**Comment by nikarh** [comment]
Hi, it would be nice if you could share more details.

1. Can you share the configuration as text and not screenshots? You can just string-replace domains with some unique IDs, so it would be easier to understand which domains are referenced where.
2. Can you show the configuration of the plugin
3. What is your Authelia version?
4. What is your Jellyfin version?

**Comment by reitenth** [comment]
![image](https://github.com/nikarh/jellyfin-plugin-authelia/assets/94771708/81cb9c35-9e30-415e-b796-c2c9ce312091)
[configuration.txt](https://github.com/nikarh/jellyfin-plugin-authelia/files/14546314/configuration.txt)

**Comment by nikarh** [comment]
I see that `Jellyfin Url` starts with an asterisk in the configuration of the plugin. I am not sure if that is a valid host name when passed to Authelia. Can you try a non-wildcard domain?

**Comment by reitenth** [comment]
i have tried using jellyfin.example.org as my url but when i log out of my jellyfin domain, it doesnt prompt authelia still

**Comment by nikarh** [comment]
Can you be more specific about what exactly you are doing and what are you expecting?

As far as I understand you

1. Have an account created in Jellyfin and are currently logged in with this account
2. You have an account in Authelia with the same or different username
3. You Sign Out in Jellyfin
4. You try signing in in Jellyfin again with the username you have in Authelia (is the same as the native account in Jellyfin?)
5. ??? No idea what you see here. Authentication error?

**Comment by reitenth** [comment]
i follow steps 1-4. when i sign out i thought this would prompt me to sign in to authelia with this ss? maybe i dont understand what this does.
![image](https://github.com/nikarh/jellyfin-plugin-authelia/assets/94771708/96c72027-bf82-4ddf-84f7-4c6057f00587)

**Comment by nikarh** [comment]
This plugin does NOT do redirects to Authelia.

The goal of this plugin is to reuse the UI and API of Jellyfin but use Authelia as an authentication backend.
With this plugin, you would use Jellyfin login screen (the one on the screenshot) and/or API, and internally it would use Authelia to check your username or password.

If want to redirect to the Authelia login page instead, you should either configure Authelia as auth plugin in your reverse proxy (e.g. with Traefik like [this](https://www.authelia.com/integration/proxies/traefik/)) or use [Jellyfin SSO Plugin](https://github.com/9p4/jellyfin-plugin-sso).

Why is this plugin reusing the form, and API? This way it works with WebOS clients and various Android clients. With the reverse proxy and SSO it would likely work only if you use Jellyfin in the web browser. 



![image](https://github.com/nikarh/jellyfin-plugin-authelia/assets/5517011/6e551e65-6d91-4f4d-920f-65bf7bbdea62)

**Comment by repparw** [comment]
> This plugin does NOT redirect to Authelia.
> 
> The goal of this plugin is to reuse the UI and API of Jellyfin but use Authelia as an authentication backend. With this plugin, you would use Jellyfin login screen (the one on the screenshot) and/or API, and internally it would use Authelia to check your username or password.
> 
> If you want to redirect to the Authelia login page instead, you should either configure Authelia as an auth plugin in your reverse proxy (e.g. with Traefik like [this](https://www.authelia.com/integration/proxies/traefik/)) or use [Jellyfin SSO Plugin](https://github.com/9p4/jellyfin-plugin-sso?rgh-link-date=2024-03-09T14%3A32%3A12.000Z).
> 
> Why is this plugin reusing the form, and API? This way it works with the WebOS client and various Android clients. Reverse proxy or SSO way would likely work only if you use Jellyfin in the web browser.
> 
> ![image](https://github.com/nikarh/jellyfin-plugin-authelia/assets/5517011/6e551e65-6d91-4f4d-920f-65bf7bbdea62)

You should probably add a gif or something showing this! It wasn't clear for me that this would not auto-redirect if logged in authelia.

I thought it would use authelia if already logged in, and fall back to jellyfin's ui if not/if app or tv

Saw a couple issues confused.

Maybe also some clarification about Access Control in Authelia (e.g DON'T put authelia in front of jellyfin, breaks apps (not specific to the plugin, but thought this dealt with it somehow))
