### ISSUE TITLE
Jellyfin 10.9.0 broke the plugin

### ISSUE THREAD

**Issue by mgabor3141** [nikarh/jellyfin-plugin-authelia#60]
I unfortunately forgot to copy the error logs before restoring, but I was getting similar messages as in  #59. Deleting cookies did not solve the issue and the login page kept giving "invalid password".

I'll see if I can add more info to this issue later.

I had to revert to [10.8.13](https://github.com/jellyfin/jellyfin/releases/tag/v10.8.13) to fix.

**Comment by nikarh** [comment]
Thanks for notifying! Slipped through due to me having pinned Jellyfin version in the personal setup.

This should be fixed in the latest version (1.0.14).
