### ISSUE TITLE
on closer inspection, does not appear to be working for me.

### ISSUE THREAD

**Issue by jamilnielsen** [nikarh/jellyfin-plugin-authelia#62]
the only way this issue affects me is having to make users myself, due to having authelia in front of everything.
so the issue is that it appears to revert/ignore authelia and simply use its own users to authenticate user/password.

here's my setup.
traefik->authelia->A,B,Jellyfin
traefik works,authelia works.
jellyfin works if i make a user manually, bypassing the use for authelia.
plugin settings:
authelia server (tried these) 192.168.0.105 , auth.redacted.org, https://auth.redacted.org
Authelia self-signed root CA: (blank) (surely traefik would not get in the way here)
create a new user on successful login = true
Jellyfin url (tried these) jellyfin.redacted.org , https://jellyfin.redacted.org

noteworthy, sometimes i see log information about 
Jellyfin.Api.Auth.CustomAuthenticationHandler: CustomAuthentication was not authenticated. Failure message: Invalid token.
Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was challenged.
im just wondering what exactly i could be doing wrong.

Expected behavior:
without local user account, if authelia account exist, create local account and login.

**Comment by jamilnielsen** [comment]
yet again figured it out.
apparently it did not auto update or anything, had to delete the plugin and re-download :)
its always the small details.

**Comment by nikarh** [comment]
Glad to know it worked in the end 🙂
